/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package aiss.tumblr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Blog {
	private Theme theme;

 	public void setTheme(Theme theme) {
		this.theme = theme;
	}

	public Theme getTheme() {
		return theme;
	}

	private java.lang.Boolean share_likes;

 	public void setShare_likes(java.lang.Boolean share_likes) {
		this.share_likes = share_likes;
	}

	public java.lang.Boolean getShare_likes() {
		return share_likes;
	}

	private java.lang.Boolean share_following;

 	public void setShare_following(java.lang.Boolean share_following) {
		this.share_following = share_following;
	}

	public java.lang.Boolean getShare_following() {
		return share_following;
	}

	private java.lang.Boolean can_be_followed;

 	public void setCan_be_followed(java.lang.Boolean can_be_followed) {
		this.can_be_followed = can_be_followed;
	}

	public java.lang.Boolean getCan_be_followed() {
		return can_be_followed;
	}

	private java.lang.Boolean active;

 	public void setActive(java.lang.Boolean active) {
		this.active = active;
	}

	public java.lang.Boolean getActive() {
		return active;
	}

	private java.lang.String name;

 	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getName() {
		return name;
	}

}