/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package aiss.tumblr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Original_size {
	private java.lang.String url;

 	public void setUrl(java.lang.String url) {
		this.url = url;
	}

	public java.lang.String getUrl() {
		return url;
	}

	private java.lang.Integer height;

 	public void setHeight(java.lang.Integer height) {
		this.height = height;
	}

	public java.lang.Integer getHeight() {
		return height;
	}

	private java.lang.Integer width;

 	public void setWidth(java.lang.Integer width) {
		this.width = width;
	}

	public java.lang.Integer getWidth() {
		return width;
	}

}