/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package aiss.tumblr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class PhotoElement {
	private java.lang.String caption;

 	public void setCaption(java.lang.String caption) {
		this.caption = caption;
	}

	public java.lang.String getCaption() {
		return caption;
	}

	private Alt_sizElement[] alt_sizes;

 	public void setAlt_sizes(Alt_sizElement[] alt_sizes) {
		this.alt_sizes = alt_sizes;
	}

	public Alt_sizElement[] getAlt_sizes() {
		return alt_sizes;
	}

	private Original_size original_size;

 	public void setOriginal_size(Original_size original_size) {
		this.original_size = original_size;
	}

	public Original_size getOriginal_size() {
		return original_size;
	}

}