/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package aiss.tumblr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Reblog {
	private java.lang.String comment;

 	public void setComment(java.lang.String comment) {
		this.comment = comment;
	}

	public java.lang.String getComment() {
		return comment;
	}

	private java.lang.String tree_html;

 	public void setTree_html(java.lang.String tree_html) {
		this.tree_html = tree_html;
	}

	public java.lang.String getTree_html() {
		return tree_html;
	}

}