/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package aiss.tumblr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ResponseElement {
	private java.lang.Object recommended_color;

 	public void setRecommended_color(java.lang.Object recommended_color) {
		this.recommended_color = recommended_color;
	}

	public java.lang.Object getRecommended_color() {
		return recommended_color;
	}

	private java.lang.Boolean display_avatar;

 	public void setDisplay_avatar(java.lang.Boolean display_avatar) {
		this.display_avatar = display_avatar;
	}

	public java.lang.Boolean getDisplay_avatar() {
		return display_avatar;
	}

	private java.lang.Boolean can_reblog;

 	public void setCan_reblog(java.lang.Boolean can_reblog) {
		this.can_reblog = can_reblog;
	}

	public java.lang.Boolean getCan_reblog() {
		return can_reblog;
	}

	private java.lang.String state;

 	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getState() {
		return state;
	}

	private java.lang.String format;

 	public void setFormat(java.lang.String format) {
		this.format = format;
	}

	public java.lang.String getFormat() {
		return format;
	}

	private java.lang.String caption;

 	public void setCaption(java.lang.String caption) {
		this.caption = caption;
	}

	public java.lang.String getCaption() {
		return caption;
	}

	private java.lang.String date;

 	public void setDate(java.lang.String date) {
		this.date = date;
	}

	public java.lang.String getDate() {
		return date;
	}

	private java.lang.String type;

 	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getType() {
		return type;
	}

	private Reblog reblog;

 	public void setReblog(Reblog reblog) {
		this.reblog = reblog;
	}

	public Reblog getReblog() {
		return reblog;
	}

	private java.lang.String image_permalink;

 	public void setImage_permalink(java.lang.String image_permalink) {
		this.image_permalink = image_permalink;
	}

	public java.lang.String getImage_permalink() {
		return image_permalink;
	}

	private java.lang.String summary;

 	public void setSummary(java.lang.String summary) {
		this.summary = summary;
	}

	public java.lang.String getSummary() {
		return summary;
	}

	private java.lang.Boolean can_reply;

 	public void setCan_reply(java.lang.Boolean can_reply) {
		this.can_reply = can_reply;
	}

	public java.lang.Boolean getCan_reply() {
		return can_reply;
	}

	private java.lang.String blog_name;

 	public void setBlog_name(java.lang.String blog_name) {
		this.blog_name = blog_name;
	}

	public java.lang.String getBlog_name() {
		return blog_name;
	}

	private java.lang.String reblog_key;

 	public void setReblog_key(java.lang.String reblog_key) {
		this.reblog_key = reblog_key;
	}

	public java.lang.String getReblog_key() {
		return reblog_key;
	}

	private java.lang.String post_url;

 	public void setPost_url(java.lang.String post_url) {
		this.post_url = post_url;
	}

	public java.lang.String getPost_url() {
		return post_url;
	}

	private java.lang.String slug;

 	public void setSlug(java.lang.String slug) {
		this.slug = slug;
	}

	public java.lang.String getSlug() {
		return slug;
	}

	private java.lang.Object recommended_source;

 	public void setRecommended_source(java.lang.Object recommended_source) {
		this.recommended_source = recommended_source;
	}

	public java.lang.Object getRecommended_source() {
		return recommended_source;
	}

	private java.lang.Integer note_count;

 	public void setNote_count(java.lang.Integer note_count) {
		this.note_count = note_count;
	}

	public java.lang.Integer getNote_count() {
		return note_count;
	}

	private java.lang.Boolean can_like;

 	public void setCan_like(java.lang.Boolean can_like) {
		this.can_like = can_like;
	}

	public java.lang.Boolean getCan_like() {
		return can_like;
	}

	private TrailElement[] trail;

 	public void setTrail(TrailElement[] trail) {
		this.trail = trail;
	}

	public TrailElement[] getTrail() {
		return trail;
	}

	private PhotoElement[] photos;

 	public void setPhotos(PhotoElement[] photos) {
		this.photos = photos;
	}

	public PhotoElement[] getPhotos() {
		return photos;
	}

	private java.lang.String[] tags;

 	public void setTags(java.lang.String[] tags) {
		this.tags = tags;
	}

	public java.lang.String[] getTags() {
		return tags;
	}

	private java.lang.Long id;

 	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Long getId() {
		return id;
	}

	private java.lang.Integer timestamp;

 	public void setTimestamp(java.lang.Integer timestamp) {
		this.timestamp = timestamp;
	}

	public java.lang.Integer getTimestamp() {
		return timestamp;
	}

	private java.lang.Boolean can_send_in_message;

 	public void setCan_send_in_message(java.lang.Boolean can_send_in_message) {
		this.can_send_in_message = can_send_in_message;
	}

	public java.lang.Boolean getCan_send_in_message() {
		return can_send_in_message;
	}

	private java.lang.String short_url;

 	public void setShort_url(java.lang.String short_url) {
		this.short_url = short_url;
	}

	public java.lang.String getShort_url() {
		return short_url;
	}

}