/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package aiss.tumblr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class SearchImages {
	private Meta meta;

 	public void setMeta(Meta meta) {
		this.meta = meta;
	}

	public Meta getMeta() {
		return meta;
	}

	private ResponseElement[] response;

 	public void setResponse(ResponseElement[] response) {
		this.response = response;
	}

	public ResponseElement[] getResponse() {
		return response;
	}

}