/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package aiss.tumblr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Theme {
	private java.lang.Boolean show_avatar;

 	public void setShow_avatar(java.lang.Boolean show_avatar) {
		this.show_avatar = show_avatar;
	}

	public java.lang.Boolean getShow_avatar() {
		return show_avatar;
	}

	private java.lang.Boolean header_stretch;

 	public void setHeader_stretch(java.lang.Boolean header_stretch) {
		this.header_stretch = header_stretch;
	}

	public java.lang.Boolean getHeader_stretch() {
		return header_stretch;
	}

	private java.lang.Boolean show_header_image;

 	public void setShow_header_image(java.lang.Boolean show_header_image) {
		this.show_header_image = show_header_image;
	}

	public java.lang.Boolean getShow_header_image() {
		return show_header_image;
	}

	private java.lang.String body_font;

 	public void setBody_font(java.lang.String body_font) {
		this.body_font = body_font;
	}

	public java.lang.String getBody_font() {
		return body_font;
	}

	private java.lang.String header_image;

 	public void setHeader_image(java.lang.String header_image) {
		this.header_image = header_image;
	}

	public java.lang.String getHeader_image() {
		return header_image;
	}

	private java.lang.Integer header_focus_height;

 	public void setHeader_focus_height(java.lang.Integer header_focus_height) {
		this.header_focus_height = header_focus_height;
	}

	public java.lang.Integer getHeader_focus_height() {
		return header_focus_height;
	}

	private java.lang.Integer header_full_height;

 	public void setHeader_full_height(java.lang.Integer header_full_height) {
		this.header_full_height = header_full_height;
	}

	public java.lang.Integer getHeader_full_height() {
		return header_full_height;
	}

	private java.lang.String title_font_weight;

 	public void setTitle_font_weight(java.lang.String title_font_weight) {
		this.title_font_weight = title_font_weight;
	}

	public java.lang.String getTitle_font_weight() {
		return title_font_weight;
	}

	private java.lang.String header_image_focused;

 	public void setHeader_image_focused(java.lang.String header_image_focused) {
		this.header_image_focused = header_image_focused;
	}

	public java.lang.String getHeader_image_focused() {
		return header_image_focused;
	}

	private java.lang.String link_color;

 	public void setLink_color(java.lang.String link_color) {
		this.link_color = link_color;
	}

	public java.lang.String getLink_color() {
		return link_color;
	}

	private java.lang.Boolean show_title;

 	public void setShow_title(java.lang.Boolean show_title) {
		this.show_title = show_title;
	}

	public java.lang.Boolean getShow_title() {
		return show_title;
	}

	private java.lang.String avatar_shape;

 	public void setAvatar_shape(java.lang.String avatar_shape) {
		this.avatar_shape = avatar_shape;
	}

	public java.lang.String getAvatar_shape() {
		return avatar_shape;
	}

	private java.lang.String title_color;

 	public void setTitle_color(java.lang.String title_color) {
		this.title_color = title_color;
	}

	public java.lang.String getTitle_color() {
		return title_color;
	}

	private java.lang.String header_image_scaled;

 	public void setHeader_image_scaled(java.lang.String header_image_scaled) {
		this.header_image_scaled = header_image_scaled;
	}

	public java.lang.String getHeader_image_scaled() {
		return header_image_scaled;
	}

	private java.lang.String background_color;

 	public void setBackground_color(java.lang.String background_color) {
		this.background_color = background_color;
	}

	public java.lang.String getBackground_color() {
		return background_color;
	}

	private java.lang.Boolean show_description;

 	public void setShow_description(java.lang.Boolean show_description) {
		this.show_description = show_description;
	}

	public java.lang.Boolean getShow_description() {
		return show_description;
	}

	private java.lang.String title_font;

 	public void setTitle_font(java.lang.String title_font) {
		this.title_font = title_font;
	}

	public java.lang.String getTitle_font() {
		return title_font;
	}

	private java.lang.String header_bounds;

 	public void setHeader_bounds(java.lang.String header_bounds) {
		this.header_bounds = header_bounds;
	}

	public java.lang.String getHeader_bounds() {
		return header_bounds;
	}

	private java.lang.Integer header_focus_width;

 	public void setHeader_focus_width(java.lang.Integer header_focus_width) {
		this.header_focus_width = header_focus_width;
	}

	public java.lang.Integer getHeader_focus_width() {
		return header_focus_width;
	}

	private java.lang.Integer header_full_width;

 	public void setHeader_full_width(java.lang.Integer header_full_width) {
		this.header_full_width = header_full_width;
	}

	public java.lang.Integer getHeader_full_width() {
		return header_full_width;
	}

}