/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package aiss.tumblr;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class TrailElement {
	private java.lang.String content_raw;

 	public void setContent_raw(java.lang.String content_raw) {
		this.content_raw = content_raw;
	}

	public java.lang.String getContent_raw() {
		return content_raw;
	}

	private java.lang.Boolean is_root_item;

 	public void setIs_root_item(java.lang.Boolean is_root_item) {
		this.is_root_item = is_root_item;
	}

	public java.lang.Boolean getIs_root_item() {
		return is_root_item;
	}

	private Blog blog;

 	public void setBlog(Blog blog) {
		this.blog = blog;
	}

	public Blog getBlog() {
		return blog;
	}

	private Post post;

 	public void setPost(Post post) {
		this.post = post;
	}

	public Post getPost() {
		return post;
	}

	private java.lang.Boolean is_current_item;

 	public void setIs_current_item(java.lang.Boolean is_current_item) {
		this.is_current_item = is_current_item;
	}

	public java.lang.Boolean getIs_current_item() {
		return is_current_item;
	}

	private java.lang.String content;

 	public void setContent(java.lang.String content) {
		this.content = content;
	}

	public java.lang.String getContent() {
		return content;
	}

}